---
- name: Deploy to Kubernetes
  hosts: localhost
  vars:
    # 'playbook_dir' is a built-in Ansible variable that always 
    # points to the 'ansible' folder where this file lives.
    # we go one level up ('..') to get to the project root.
    project_root: "{{ playbook_dir }}/.."
  tasks:
    - name: Apply namespace
      command: kubectl apply -f "{{ project_root }}/k8s/00-namespace.yaml"

    - name: Deploy PostgreSQL
      command: kubectl apply -f "{{ project_root }}/k8s/01-postgres-deployment.yaml"

    - name: Deploy User Service
      command: kubectl apply -f "{{ project_root }}/k8s/06-user-service-deployment.yaml"