name: Local Pipeline

on:
  push:
    branches:
      - feature/ci-cd
      - develop
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ github.sha }} .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ github.sha }}

      - name: Deploy to Minikube via Ansible
        run: wsl ansible-playbook ansible/deploy.yml
